TYPE=VIEW
query=select distinct `teasystem`.`brand`.`brandname` AS `brandname` from `teasystem`.`brand`
md5=bb663c787126bb4d92f4801bd78b4f8a
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2022-01-10 11:16:37
create-version=2
source=SELECT DISTINCT `brandname` FROM `brand`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select distinct `teasystem`.`brand`.`brandname` AS `brandname` from `teasystem`.`brand`
mariadb-version=100422
